# Generated by Django 4.0.4 on 2022-05-11 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery')),
                ('title', models.CharField(max_length=255)),
                ('publication_date', models.DateField(auto_now_add=True)),
                ('category', models.ManyToManyField(related_name='category', to='category.category')),
            ],
        ),
    ]
