# Generated by Django 4.0.4 on 2022-05-11 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faith',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='faith_lift')),
                ('video', models.FileField(blank=True, null=True, upload_to='faith_lift/%y')),
                ('content', models.CharField(blank=True, max_length=200, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('category', models.ManyToManyField(related_name='faith_category', to='category.category')),
            ],
            options={
                'ordering': ['date_added'],
            },
        ),
    ]
