# Generated by Django 4.0.4 on 2022-05-13 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sermon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(db_index=True, max_length=200)),
                ('preached_by', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=1000)),
                ('video', models.FileField(upload_to='movies/%')),
                ('image', models.ImageField(upload_to='movies')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('views_count', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ManyToManyField(related_name='sermon_category', to='category.category')),
                ('language', models.ManyToManyField(related_name='language', to='sermon.language')),
                ('status', models.ManyToManyField(blank=True, related_name='status', to='sermon.status')),
            ],
            options={
                'ordering': ['date_added'],
            },
        ),
    ]
