# Generated by Django 4.0.4 on 2022-05-13 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name_plural': 'Status',
            },
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='payroll/%y')),
                ('position', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('id_number', models.CharField(max_length=4)),
                ('contact', models.CharField(max_length=20)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=4, null=True)),
                ('salary', models.IntegerField(blank=True, null=True)),
                ('allowance', models.IntegerField(blank=True, null=True)),
                ('accomodation', models.IntegerField(blank=True, null=True)),
                ('date_employed', models.DateField()),
                ('bank_name', models.CharField(max_length=255)),
                ('account_title', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=255)),
                ('nok_name', models.CharField(max_length=255)),
                ('nok_address', models.CharField(max_length=255)),
                ('nok_contact', models.CharField(max_length=20)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('sum', models.IntegerField()),
                ('status', models.ManyToManyField(related_name='payroll_status', to='expense.status')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('name', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('status', models.ManyToManyField(related_name='maintenance_status', to='expense.status')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Charity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='charity')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('description', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('category', models.ManyToManyField(related_name='charity_category', to='expense.category')),
                ('status', models.ManyToManyField(related_name='charity_status', to='expense.status')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
