# Generated by Django 4.0.4 on 2022-05-13 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0003_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.ManyToManyField(related_name='payment_status', to='expense.status'),
        ),
    ]
